//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pnthanh_k22cntt_2210900066_prj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int id { get; set; }
        public Nullable<int> idDonHang { get; set; }
        public Nullable<int> idPhuongThucThanhToan { get; set; }
        public System.DateTime ngayThanhToan { get; set; }
        public double soTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
